### ISSUE TITLE
코드리뷰

### ISSUE THREAD

**Issue by skt-t1-byungi** [skt-t1-byungi/use-simple-store#6]

**Comment by shs400** [comment]
https://github.com/skt-t1-byungi/use-simple-store/blob/c5c0bb7e48d4aaac2e620bdec6694467d91f5006/src/index.ts#L67

passThrough 함수의 용도는 무엇인가요??
값을 받아 그대로 리턴하는데 단순히 타입을 체크?하기위한 용도인건지 궁금합니다.

**Comment by shs400** [comment]
https://github.com/skt-t1-byungi/use-simple-store/blob/c5c0bb7e48d4aaac2e620bdec6694467d91f5006/src/index.ts#L49

useEffect가 아닌 useLayoutEffect 사용 이유가 무엇인지 궁금합니다.
동기 처리를 위해서 사용된것인가요..?

**Comment by ethan-heo** [comment]
https://github.com/skt-t1-byungi/use-simple-store/blob/0b93e00ccdd6549b19da3477d4e8ba223c6a5422/src/index.ts#L27

같은 객체를 비교하는데 참조비교가 달라지는게 신기하네요. 그리고 반대로 비교하면 같다고 나오는데 비교 순서가 어떻게 되는지 궁금하네요.

**Comment by goldenthumb** [comment]
https://github.com/skt-t1-byungi/use-simple-store/blob/0b93e00ccdd6549b19da3477d4e8ba223c6a5422/src/index.ts#L49

혹시 두번째 인자가 보이지 않는데 의도된건가요?

**Comment by afrontend** [comment]
https://github.com/skt-t1-byungi/use-simple-store/blob/0b93e00ccdd6549b19da3477d4e8ba223c6a5422/src/index.ts#L35-L37

아래 처럼 변경해도 될까요?

        const isNotSameListener = (l: Listener<T>) => {
            return !(l === listener)
        };

        function removeListenerFrom(listeners: Listener<T>[]) {
            return listeners.filter(isNotSameListener)
        }

        return () => {
            this._listeners = removeListenerFrom(this._listeners)
        }

코드는 늘어나지만 리턴하는 마지막 줄만 본다면 좀 더 읽기 쉬워진다고 생각했습니다.

**Comment by afrontend** [comment]
https://github.com/skt-t1-byungi/use-simple-store/blob/0b93e00ccdd6549b19da3477d4e8ba223c6a5422/src/index.ts#L26

produce를 사용한 이유를 알고 싶어요.

**Comment by goldenthumb** [comment]
https://github.com/skt-t1-byungi/use-simple-store/blob/0b93e00ccdd6549b19da3477d4e8ba223c6a5422/src/index.ts#L49-L53

위의 코드랑 아래코드랑 성능상 차이가 많이 있을까요? 그리고 useState 를 사용하지 않고 useRef 를 사용하신 이유가 있으실까요 제가 이해를 잘 못해서 이쪽 부분이 계속 뭔가 신경이 쓰이네요.

```javascript
useLayoutEffect(() => { 
  selectorRef.current = currSelector;
  if (!stateRef.current) stateRef.current = currSelector(this._state);
}) 
```

**Comment by 4sizn** [comment]
코드 흐름상 useLayoutEffect코드가
아래 if 코드에 영향을 줄 것이라 생각했습니다.

useLayoutEffect 코드가 if 비교 구문 아래 위치에 놓이는건 어떻게 생각하시나요?

https://github.com/skt-t1-byungi/use-simple-store/blob/0b93e00ccdd6549b19da3477d4e8ba223c6a5422/src/index.ts#L49-L53

       if (stateRef.current === undefined || currSelector !== selectorRef.current) {
                stateRef.current = currSelector(this._state)
            }

             useLayoutEffect(() => { selectorRef.current = currSelector })
             useLayoutEffect(() => this.subscribe(() => {
            const nextState = selectorRef.current(this._state)
            if (!equal(stateRef.current, nextState)) {
                stateRef.current = nextState
                forceUpdate()
            }
        }), [])
